version: "3.7"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=skyvern
      - POSTGRES_PASSWORD=skyvern
      - POSTGRES_DB=skyvern
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skyvern"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern:
    image: public.ecr.aws/skyvern/skyvern:latest
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./log:/data/log
      - ./.streamlit:/app/.streamlit
    env_file:
      - .env
    # If you need to override anything beyond what's in .env, do it here:
    environment:
      - DATABASE_STRING=postgresql+psycopg://skyvern:skyvern@postgres:5432/skyvern
      # If you specifically want a headful browser in production:
      - BROWSER_TYPE=chromium-headful
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.streamlit/secrets.toml"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: on-failure
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./.streamlit:/app/.streamlit
    env_file:
      - .env
    # Overwrite only if needed:
    environment:
      # Switch to https and wss if your domain is served over TLS
      - VITE_WSS_BASE_URL=ws://skyvern-u32695.vm.elestio.app/api/v1
      - VITE_API_BASE_URL=http://skyvern-u32695.vm.elestio.app/api/v1
      - VITE_ARTIFACT_API_BASE_URL=http://skyvern-u32695.vm.elestio.app:9090
    depends_on:
      skyvern:
        condition: service_healthy
